Repository Phonesonal-Trainer/BE, pull requests merged in 2025-08, with the labels that each got.

#46 칼로리, 시간, 목표 엔티티 변경
  src/main/java/Phonesonal/PhoneBE/domain/User.java
  src/main/java/Phonesonal/PhoneBE/domain/common/GoalPeriod.java
  src/main/java/Phonesonal/PhoneBE/domain/common/exercise/DailyExerciseRecord.java
  src/main/java/Phonesonal/PhoneBE/domain/common/exercise/Exercise.java
  src/main/java/Phonesonal/PhoneBE/domain/mapping/UserExercise.java
  src/main/java/Phonesonal/PhoneBE/repository/DailyCalorieRepository.java
  src/main/java/Phonesonal/PhoneBE/repository/DailyExerciseRecordRepository.java
  src/main/java/Phonesonal/PhoneBE/service/ExerciseServiceImpl.java
  src/main/java/Phonesonal/PhoneBE/web/controller/UserExerciseController.java
  src/main/java/Phonesonal/PhoneBE/web/dto/Exercise/response/UserExerciseResponseDTO.java
Labels: ✨feature

#74 Leo/refactor/exercise#1
  src/main/java/Phonesonal/PhoneBE/domain/common/WeeklyStamp.java
  src/main/java/Phonesonal/PhoneBE/domain/common/exercise/Exercise.java
  src/main/java/Phonesonal/PhoneBE/domain/common/exercise/ExerciseDescription.java
  src/main/java/Phonesonal/PhoneBE/service/ExerciseServiceImpl.java
  src/main/java/Phonesonal/PhoneBE/service/WeeklyStampService.java
  src/main/java/Phonesonal/PhoneBE/service/WeeklyStampServiceImpl.java
  src/main/java/Phonesonal/PhoneBE/web/controller/WeeklyStampController.java
  src/main/java/Phonesonal/PhoneBE/web/dto/Exercise/response/ExerciseDetailResponseDTO.java
Labels: ♻️refactor

#78 운동 계산식 리펙토링
  src/main/java/Phonesonal/PhoneBE/service/Home/HomeServiceImpl.java
  src/main/java/Phonesonal/PhoneBE/service/Report/ReportQueryServiceImpl.java
Labels: ♻️refactor

#82 ♻️ 세트 휴식시간 리펙토링
  src/main/java/Phonesonal/PhoneBE/apiPayload/code/status/ErrorStatus.java
  src/main/java/Phonesonal/PhoneBE/domain/enums/exercise/State.java
  src/main/java/Phonesonal/PhoneBE/domain/mapping/UserExercise.java
  src/main/java/Phonesonal/PhoneBE/service/ExerciseService.java
  src/main/java/Phonesonal/PhoneBE/service/ExerciseServiceImpl.java
  src/main/java/Phonesonal/PhoneBE/web/controller/UserExerciseController.java
  src/main/java/Phonesonal/PhoneBE/web/dto/Exercise/response/UserExerciseResponseDTO.java
Labels: ♻️refactor

#87 refactor: ios 구조식 앱스킴 리다이렉트
  src/main/java/Phonesonal/PhoneBE/web/controller/AuthController.java
Labels: ♻️refactor

#121 운동버그수정
  src/main/java/Phonesonal/PhoneBE/service/Exercise/ExerciseService.java
  src/main/java/Phonesonal/PhoneBE/service/Exercise/ExerciseServiceImpl.java
  src/main/java/Phonesonal/PhoneBE/web/controller/UserExerciseController.java
  src/main/java/Phonesonal/PhoneBE/web/dto/Exercise/response/DailyExerciseDTO.java
  src/main/java/Phonesonal/PhoneBE/web/dto/Exercise/response/UserExerciseResponseDTO.java
Labels: 🐛bug
